import { useState, useEffect, useCallback, useRef, useMemo } from 'react';
import { apiFetch } from './utils/api';
import { useMarketData } from './hooks/useMarketData';
import { useWebSocket } from './hooks/useWebSocket';
import { useAuth } from './context/AuthContext';
import { useSettings } from './context/SettingsContext';
import { PriceProvider } from './context/PriceContext';
import { FeedStatusProvider } from './context/FeedStatusContext';
import { WatchlistProvider } from './context/WatchlistContext';
import { MarketProvider, useMarketDispatch } from './context/MarketContext';
import { DragProvider } from './context/DragContext';
import { IndexPanel } from './components/panels/IndexPanel';
import { StockPanel } from './components/panels/StockPanel';
import { ForexPanel } from './components/panels/ForexPanel';
import { CommoditiesPanel } from './components/panels/CommoditiesPanel';
import { CryptoPanel } from './components/panels/CryptoPanel';
import { NewsPanel } from './components/panels/NewsPanel';
import { ChartPanel } from './components/panels/ChartPanel';
import { SentimentPanel } from './components/panels/SentimentPanel';
import { SearchPanel } from './components/panels/SearchPanel';
import { DICurvePanel } from './components/panels/DICurvePanel';
import DebtPanel from './components/panels/DebtPanel';
import BrazilPanel from './components/panels/BrazilPanel';
import GlobalIndicesPanel from './components/panels/GlobalIndicesPanel';
import WatchlistPanel from './components/panels/WatchlistPanel';
import HumidityPanel from './components/panels/HumidityPanel';
import HomePanel from './components/panels/HomePanel';
import HomePanelMobile from './components/panels/HomePanelMobile';)
