/**
 * AppBoundaries.jsx — #253 P3.1 extract of shell-level UI primitives from App.jsx.
 *
 * These have no business logic and never change. Keeping them next to App.jsx
 * was bloat — they belong with the other app-shell helpers under components/app.
 *
 *   - TermsAcceptanceModal: first-run TOS gate (scroll-to-bottom + accept)
 *   - AppErrorBoundary:     top-level React error boundary (render crash screen)
 *   - ScreenFallback:       Suspense fallback for lazy panels
 *   - InstrumentDetailSkeleton: shimmer placeholder while InstrumentDetail loads
 */

import { useState, useRef, useCallback, useEffect, Component } from 'react';

// ── Terms of Service acceptance modal ──────────────────────────────────────
export function TermsAcceptanceModal({ onAccept }) {
  const [scrolledToBottom, setScrolledToBottom] = useState(false);
  const contentRef = useRef(null);

  const handleScroll = useCallback(() => {
    const el = contentRef.current;
    if (!el) return;
    if (el.scrollTop + el.clientHeight >= el.scrollHeight - 30) {
      setScrolledToBottom(true);
    }
  }, []);

  // If there is nothing to scroll, there is nothing to wait for.
  //
  // This gate used to be satisfiable ONLY from inside handleScroll, so when the
  // terms box was not taller than its container no scroll event ever fired, the
  // button stayed disabled forever and the user was permanently locked out of the
  // app -- unable to accept, unable to continue. It reproduced on any tall window,
  // at reduced browser zoom, or if the copy ever got shorter.
  //
  // Re-checked on mount and via ResizeObserver, because whether the content
  // overflows depends on the viewport and can change after fonts load or on
  // rotate/resize.
  useEffect(() => {
    const el = contentRef.current;
    if (!el) return undefined;

    const check = () => {
      // A 2px tolerance absorbs sub-pixel layout rounding.
      if (el.scrollHeight <= el.clientHeight + 2) {
        setScrolledToBottom(true);
      }
    };

    check();

    let ro;
    if (typeof ResizeObserver === 'function') {
      ro = new ResizeObserver(check);
      ro.observe(el);
    }
    window.addEventListener('resize', check);
    return () => {
      if (ro) ro.disconnect();
      window.removeEventListener('resize', check);
    };
  }, []);

  return (
    <div style={{
      position: 'fixed', inset: 0, zIndex: 99999,
      background: 'rgba(0,0,0,0.85)', backdropFilter: 'blur(8px)',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      padding: 16,
    }}>
      <div style={{
        background: 'var(--bg-secondary)', borderRadius: 12,
        maxWidth: 520, width: '100%', maxHeight: '80vh',
        display: 'flex', flexDirection: 'column',
        border: '1px solid var(--border-subtle)',
        boxShadow: '0 24px 48px rgba(0,0,0,0.5)',
      }}>
        <div style={{
          padding: '20px 24px 12px', borderBottom: '1px solid var(--border-subtle)',
        }}>
          <div style={{ color: 'var(--accent)', fontSize: 10, fontWeight: 700, letterSpacing: '1.5px', marginBottom: 4 }}>PARTICLE</div>
          <div style={{ color: 'var(--text-primary)', fontSize: 18, fontWeight: 600 }}>Terms of Service</div>
          <div style={{ color: 'var(--text-faint)', fontSize: 12, marginTop: 4 }}>Please review and accept to continue</div>
        </div>
        <div
          ref={contentRef}
          onScroll={handleScroll}
          style={{
            flex: 1, overflow: 'auto', padding: '16px 24px',
            fontSize: 12, lineHeight: 1.7, color: 'var(--text-secondary)',
            maxHeight: '50vh',
          }}
        >
          <p style={{ marginBottom: 12 }}>By using Particle Market Terminal, you agree to the following terms:</p>
          <p style={{ marginBottom: 12 }}><strong style={{ color: 'var(--text-primary)' }}>Financial Disclaimer:</strong> All data and information provided through Particle Market Terminal is for informational and educational purposes only. It should not be construed as financial advice, investment recommendations, or an offer to buy or sell securities.</p>
          <p style={{ marginBottom: 12 }}><strong style={{ color: 'var(--text-primary)' }}>No Guarantee of Accuracy:</strong> While we strive for accuracy, market data may be delayed or contain errors. Particle makes no warranty regarding the completeness or reliability of any information displayed.</p>
          <p style={{ marginBottom: 12 }}><strong style={{ color: 'var(--text-primary)' }}>AI-Generated Content:</strong> Some content is generated by artificial intelligence models and may contain inaccuracies. AI-generated insights do not constitute professional financial advice.</p>
          <p style={{ marginBottom: 12 }}><strong style={{ color: 'var(--text-primary)' }}>User Responsibility:</strong> You are solely responsible for your investment decisions. Past performance does not guarantee future results. Always consult a qualified financial advisor before making investment decisions.</p>
          <p style={{ marginBottom: 12 }}><strong style={{ color: 'var(--text-primary)' }}>Subscription & Billing:</strong> Your subscription is governed by the billing terms presented at checkout. Cancellations take effect at the end of the current billing period.</p>
          <p style={{ marginBottom: 12, color: 'var(--text-faint)', fontSize: 11 }}>For the full Terms of Service, visit <a href="/terms" target="_blank" rel="noopener noreferrer" style={{ color: 'var(--accent)' }}>particle.market/terms</a></p>
        </div>
        <div style={{
          padding: '16px 24px 20px', borderTop: '1px solid var(--border-subtle)',
          display: 'flex', flexDirection: 'column', gap: 8,
        }}>
          <button
            onClick={onAccept}
            disabled={!scrolledToBottom}
            style={{
              width: '100%', padding: '12px 0', borderRadius: 8,
              background: 'var(--accent)', color: 'var(--color-text-inverse)',
              fontWeight: 600, fontSize: 14, border: 'none',
              cursor: scrolledToBottom ? 'pointer' : 'not-allowed',
              opacity: scrolledToBottom ? 1 : 0.45, transition: 'opacity 150ms',
            }}
          >
            {scrolledToBottom ? 'I Accept the Terms of Service' : 'Scroll to the bottom to accept'}
          </button>
          <div style={{ textAlign: 'center', fontSize: 10, color: 'var(--text-faint)' }}>
            Data provided for informational purposes only. Not financial advice.
          </div>
        </div>
      </div>
    </div>
  );
}

// ── Error Boundary — catches runtime crashes and shows diagnostic info ─────
function isChunkLoadError(err) {
  if (!err) return false;
  const name = err.name || '';
  const msg = String(err.message || '');
  return (
    name === 'ChunkLoadError' ||
    /Failed to fetch dynamically imported module/i.test(msg) ||
    /Loading chunk [\d]+ failed/i.test(msg) ||
    /Importing a module script failed/i.test(msg) ||
    /dynamically imported module/i.test(msg)
  );
}
const _APP_RELOAD_KEY = 'particle_app_reload';
function _appReloadedRecently() {
  try { return Date.now() - Number(sessionStorage.getItem(_APP_RELOAD_KEY) || 0) < 20000; } catch { return false; }
}
function _appMarkReload() {
  try { sessionStorage.setItem(_APP_RELOAD_KEY, String(Date.now())); } catch { /* storage off */ }
}

export class AppErrorBoundary extends Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false, error: null, errorInfo: null };
  }
  static getDerivedStateFromError(error) {
    return { hasError: true, error };
  }
  componentDidCatch(error, errorInfo) {
    this.setState({ errorInfo });
    console.error('[AppErrorBoundary] Caught render crash:', error, errorInfo);
    // Stale-deploy chunk 404 (a new client bundle rotated the hashes) -> pull
    // the fresh index once. Guarded so a genuinely missing chunk can't loop.
    if (isChunkLoadError(error) && !_appReloadedRecently()) {
      _appMarkReload();
      window.location.reload();
    }
  }
  render() {
    if (this.state.hasError) {
      return (
        <div style={{
          position: 'fixed', inset: 0, background: '#0a0a0a',
          display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
          color: 'var(--color-text-primary)', fontFamily: 'var(--font-family-mono)', padding: 24, gap: 16,
        }}>
          <div style={{ color: 'var(--color-accent)', fontWeight: 700, fontSize: 13, letterSpacing: '3px' }}>PARTICLE</div>
          <div style={{ color: 'var(--color-down)', fontSize: 14, fontWeight: 600 }}>
            {isChunkLoadError(this.state.error) ? 'Updating to the latest version…' : 'App crashed — render error'}
          </div>
          <div style={{ color: '#ff9900', fontSize: 11, maxWidth: 600, wordBreak: 'break-word', textAlign: 'center' }}>
            {isChunkLoadError(this.state.error)
              ? 'A new version was deployed. Reload to get the update.'
              : (this.state.error?.message || 'Unknown error')}
          </div>
          {!isChunkLoadError(this.state.error) && (
            <pre style={{ color: '#888', fontSize: 9, maxWidth: '90vw', maxHeight: '40vh', overflow: 'auto', whiteSpace: 'pre-wrap' }}>
              {this.state.error?.stack || ''}{'\n'}{this.state.errorInfo?.componentStack || ''}
            </pre>
          )}
          <button
            onClick={() => { this.setState({ hasError: false, error: null, errorInfo: null }); window.location.reload(); }}
            style={{ background: 'var(--color-particle)', color: 'var(--color-text-inverse)', border: 'none', padding: '8px 24px', borderRadius: 4, cursor: 'pointer', fontSize: 12, letterSpacing: '1px' }}
          >RELOAD</button>
        </div>
      );
    }
    return this.props.children;
  }
}

// ── Lazy-load fallback — matches dark terminal aesthetic ──────────────────────────
export function ScreenFallback() {
  return (
    <div style={{
      flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center',
      background: 'var(--bg-panel)', color: 'var(--text-faint)', fontSize: 12,
      fontFamily: 'var(--font-mono)', letterSpacing: '1px',
    }}>
      <div style={{ textAlign: 'center' }}>
        <div style={{ color: 'var(--accent)', fontSize: 11, marginBottom: 8 }}>LOADING</div>
        <div className="boot-bar" style={{ width: 120, height: 2, margin: '0 auto' }}>
          <div className="boot-bar-fill" />
        </div>
      </div>
    </div>
  );
}

// ── InstrumentDetail skeleton (shimmer placeholder) ──────────────────────────
export function InstrumentDetailSkeleton() {
  return (
    <div style={{
      position: 'fixed', inset: 0, zIndex: 9999,
      background: 'rgba(0, 0, 0, 0.97)',
      display: 'flex', flexDirection: 'column',
      fontFamily: 'var(--font-ui)', color: 'var(--text-primary)',
    }}>
      {/* Header skeleton */}
      <div style={{
        display: 'flex', alignItems: 'center', gap: 10,
        padding: '8px 16px', borderBottom: '1px solid var(--border-default)',
        background: 'var(--bg-panel)',
      }}>
        <div className="skeleton-shimmer" style={{ width: 32, height: 32, borderRadius: '50%' }} />
        <div className="skeleton-shimmer" style={{ width: 80, height: 18, borderRadius: 4 }} />
        <div className="skeleton-shimmer" style={{ width: 120, height: 14, borderRadius: 4 }} />
        <div style={{ flex: 1 }} />
        <div className="skeleton-shimmer" style={{ width: 100, height: 24, borderRadius: 4 }} />
        <div className="skeleton-shimmer" style={{ width: 80, height: 18, borderRadius: 4 }} />
      </div>
      {/* Chart skeleton */}
      <div style={{ flex: 1, padding: 16, display: 'flex', flexDirection: 'column', gap: 12 }}>
        <div className="skeleton-shimmer" style={{ width: '100%', height: 300, borderRadius: 8 }} />
        {/* Metrics strip skeleton */}
        <div style={{ display: 'flex', gap: 8 }}>
          {[1,2,3,4,5].map(i => (
            <div key={i} className="skeleton-shimmer" style={{ flex: 1, height: 48, borderRadius: 6 }} />
          ))}
        </div>
        {/* Fundamentals skeleton */}
        <div className="skeleton-shimmer" style={{ width: '100%', height: 200, borderRadius: 8 }} />
      </div>
    </div>
  );
}
